language: scala

env:
  global:
    - JAVA_OPTS="-DSKIP_FLAKY=true -Dsbt.log.noformat=true"

  matrix:
    - PROJECT=benchmarks
    - PROJECT=http

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.dodo

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

scala:
  - 2.11.11
  - 2.12.4

jdk:
  - oraclejdk8

before_script:
  # default $SBT_OPTS is irrelevant to sbt launcher
  - unset SBT_OPTS
  - curl -s https://raw.githubusercontent.com/twitter/dodo/develop/bin/build | bash -s -- --no-test finatra
  - travis_retry ./sbt --error ++$TRAVIS_SCALA_VERSION update

script:
  # run for all environments
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION coverage "$PROJECT/test" coverageReport

after_success:
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - bash <(curl -s https://codecov.io/bash)
